[global]
progress_full_character = "="
progress_empty_character = "="
progress_prefix = "["
progress_suffix = "]"
time_format = "%Y-%m-%d %H:%M:%S"

[banner]
color = "red"
command = "hostname | figlet -f slant"
# if you don't want a dependency on figlet, you can generate your
# banner however you want, put it in a file, and then use something like:
# command = "cat banner.txt"

[weather]
url = "https://wttr.in/Bordeaux?0"

[service_status]
iwd = "iwd"

[uptime]
prefix = "Up"

[user_service_status]
gpg-agent = "gpg-agent"

# [ssl_certificates]
# sort_method = "manual"
#
#    [ssl_certificates.certs]
#    CertName1 = "/path/to/cert1.pem"
#    CertName2 = "/path/to/cert2.pem"

[filesystems]
root = "/"

# [fail_2_ban]
# jails = ["sshd", "anotherjail"]

[last_login]
nicolas = 1

[last_run]