#!/usr/bin/env sh

# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Spaces
yabai -m space 1 --label "1"
yabai -m space 2 --label "2"
yabai -m space 3 --label "3"
yabai -m space 4 --label "4"
yabai -m space 5 --label "5"
yabai -m space 6 --label "6"
yabai -m space 7 --label "7"
yabai -m space 8 --label "8"
yabai -m space 9 --label "9"
yabai -m space 10 --label "10"

# global settings
yabai -m config auto_balance                 off
yabai -m config focus_follows_mouse          on
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config mouse_follows_focus          on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config split_ratio                  0.50

# window opacities
yabai -m config window_opacity               off
yabai -m config window_placement             second_child
yabai -m config window_shadow                off
yabai -m config window_topmost               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

# window borders
yabai -m config window_border                off
# yabai -m config window_border_width          0.1
yabai -m config active_window_border_color   0x00292929
yabai -m config normal_window_border_color   0x00292929

# general space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m config top_padding                  0

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config external_bar                 all:0:25

# Do not manage some apps which are not resizable
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app='^Preview$' manage=off
yabai -m rule --add app='^Finder$' manage=on
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app='^Spotify$' manage=on
yabai -m rule --add app='^Signal$' manage=off

echo "yabai configuration loaded.."
