#!/usr/bin/env sh

# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

### Variables ###

export external_bar_height="24"   # Height of top bar in pt                                         (usage: 24/16/any number)
export shadow_toggle="off"        # Determines wether window shadows are on                         (usage: on/off)
export border_toggle="on"         # Determines wether borders for active windows are on             (usage: on/off)
export border_width="2"           # Determines the width of the active window's border              (usage: 2/5/any number)
export border_radius="11"         # radius of the active window's border                            (usage: 11/0/any number)
export opacity_toggle="off"       # Detriments wether opacity based focus is on                     (usage: on/off)
export layout="bsp"               # Layout of windows                                               (usage: bsp/float/stack)
export gap_width="35"             # width of window gaps                                            (usage: 17/8/any number)
export animation_duration="0"     # Window animation duration                                       (usage: 0.0/0.3/0.5)

### Load scriptting adittion ##
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"  # If yabai detected that i loaded the scripting addition, restart yabai

### Focus the window that is hoverd with the mouse ###
yabai -m config focus_follows_mouse autoraise

### Toggles ###
yabai -m config external_bar all:$external_bar_height:0          # height of external bar (configured in variables)
yabai -m config window_shadow $shadow_toggle                     # turn on/off window shadows (configured in variables)
yabai -m config layout $layout                                   # set layout (configured in variables)
yabai -m config window_animation_duration $animation_duration    # Set animation duration (configured in variables)
yabai -m config window_border_radius $border_radius              # set border radius (configured in variables)

### Configure opacity based focus ###
yabai -m config window_opacity             $opacity_toggle      # Turn on/off opacity based focus (configured in variables)
yabai -m config window_opacity_duration    0.2                  # Time it takes to fade between windows
yabai -m config active_window_opacity      1.0                  # opacity for the focused window
yabai -m config normal_window_opacity      0.9                  # opacity for other windows

### Confgure mouse usage ###
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize


### Configure window borders ###
yabai -m config window_border $border_toggle            # Turn on/off window borders (configured in variables)
yabai -m config window_border_width $border_width       # Set border width (configured in variables)
yabai -m config active_window_border_color 0xFF6faec0   # Set border color for the active window
yabai -m config normal_window_border_color 0xFF3e4050   # set border color for other windows

### Configure window gaps ###
yabai -m config top_padding                8   # Top gap width (configured in variables)
yabai -m config bottom_padding             10   # Bottom gap width (configured in variables)
yabai -m config left_padding               10   # left gap width (configured in variables)
yabai -m config right_padding              10   # right gap width (configured in variables)
yabai -m config window_gap                 8   # inside gap width (configured in variables)

### Window rules/exeptions ###
yabai -m rule --add app="^(Calculator||Spotify|zoom.us|Photo Booth|Archive Utility|System Settings|Karabiner-EventViewer|Karabiner-Elements|Alfred Preferences|)$" manage=off  # Don't tile unresizable apps

### Space labels ###

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 home
setup_space 2 workterm
setup_space 3 chat
setup_space 4 workterm
setup_space 5 misc
setup_space 6 myweb
setup_space 7 music
setup_space 8 myterm

# yabai -m rule --add app="^Brave Browser$" space=^2

### Sketchybar ###
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"         # Notify sketchybar when space changes
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change"   # Notify sketchybar when the focused app changes

# Do not manage some apps which are not resizable
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

### Notify when the yabai config finished loading ###
echo "yabai configuration loaded.."
