.TH PostgreSQL Cheatsheet 7 2019-07-06 "PostgreSQL Cheatsheet" "Nicolas Lamirault"
.SH NAME
PostgreSQL \- Cheatsheet
.SH SYNOPSIS
.PP
Cheatsheet for PostgreSQL
.\" .SH NOTE
.\" .PP
.\" .SH DESCRIPTION
.\" .PP

.\" -------------------------------------------------------------------------

.SH Core

.SS Connection
.PP
psql -h host -U dbname=db

.SS Switch connection to a new database
.PP
\\c dbname [ username ]

.SS List available databases
.PP
\\l

.SS List tables inside public schemas
.PP
\\dt

.SS List tables inside particular schemas. For eg: 'schema1'.
.PP
\\dt schema1

.SS Describe a table
.PP
\\d table_name

.SS List available schema
.PP
\\dn

.SS List available functions
.PP
\\df

.SS List available views
.PP
\\dv

.SS List users and their roles
.PP
\\du

.SS Check Table Privileges (See links)
.PP
\\z "TableNameOrView"

.SS Command history
.PP
\\s

.SS Execute psql commands from a file
.PP
\\i filename

.SS Get help on psql commands
.PP
\\?

.SS Get help on specific PostgreSQL statement
.PP
\\h ALTER TABLE

.SS Switch output options
.PP
\\a command switches from aligned to non-aligned column output.
.PP
\\H command formats the output to HTML format.

.SH Transations

.SS Execute a transation
.PP
begin;
.PP
sql request;
.PP
commit;

.SS Rollback
.PP
begin;
.PP
sql request;
.PP
rollback;

.SS Dump table to file
.PP
\\copy table_name to 'filename.csv' csv header

.SS Dump requests into CSV file
.PP
psql>\\f ','
.PP
psql>\\a
.PP
psql>\\o '/tmp/sql.csv'
.PP
psql> select ....
.PP
psql>\\q

.\" -------------------------------------------------------------------------

.SH SEE ALSO
.I \%https://postgresql.org

.I \%https://www.postgresql.org/docs/current/ddl-priv.html#PRIVILEGE-ABBREVS-TABLE
