.TH Systeld Cheatsheet 7 2019-03-28 "Kubernetes Cheatsheet" "Nicolas Lamirault"
.SH NAME
Systemd \- Cheatsheet
.SH SYNOPSIS
.PP
Cheatsheet for Systemd

.\" .SH NOTE
.\" .PP
.\" .SH DESCRIPTION
.\" .PP

.\" -------------------------------------------------------------------------

.SH Analyze the system

.SS Global status
.PP
systemctl status

.SS List all running units
.PP
systemctl list-units

.SS List of all failed units
.PP
systemctl --failed

.SS List of all installed units
.PP
systemctl list-unit-files

.\" -------------------------------------------------------------------------

.SH Usings units

.SS Manage units
.PP
systemctl start|stop|restart|reload|status unit

.SS State of an unit
.PP
systemctl is-enabled|enable|disable|mask|unmask unit

.SS Reload systemd manager configuration
.PP
systemctl daemon-reload

.\" -------------------------------------------------------------------------

.SH Exploring units

.SS Display unit's description file
.PP
systemctl cat unit

.SS Add a snippet to an existing unit file
.PP
systemctl edit unit

.SS Edit the unit
.PP
systemctl edit --full unit

.SS Dependencies of an unit
.PP
systemctl list-dependencies unit

.SS Low levels details of an unit
.PP
systemctl show unit


.\" -------------------------------------------------------------------------

.SH System logs informations

.SS See all log information that journald has collected (since boot)
.PP
journalctl (-b)

.SS All messages from a specific date
.PP
journalctl --since="2018-10-30 18:17:16"

.SS All messages since 20 minutes
.PP
journalctl --since "20 min ago"


.\" -------------------------------------------------------------------------

.SH SEE ALSO
.I \%https://www.freedesktop.org/wiki/Software/systemd/
.I \%https://github.com/systemd/systemd
