#!/usr/bin/bash

# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

. "${HOME}/.config/sketchybar/env.sh"

# Needs to have Regular, Bold, Semibold, Heavy and Black variants
# FONT="SF Pro"
FONT="Hack Nerd Font"

# Setting up the general bar appearance and default values
sketchybar \
    --bar height=39            \
          color="${BAR_COLOR}" \
          shadow=on            \
          position=top         \
          sticky=on            \
          padding_right=10     \
          padding_left=10      \
          corner_radius=9      \
          y_offset=10          \
          margin=10            \
          blur_radius=20       \
          notch_width=0        \
    --default updates=when_shown                                    \
              icon.font="${FONT}:Bold:14.0"                         \
              icon.color="${ICON_COLOR}"                            \
              icon.padding_left="${PADDINGS}"                       \
              icon.padding_right="${PADDINGS}"                      \
              label.font="${FONT}:Semibold:13.0"                    \
              label.color="${LABEL_COLOR}"                          \
              label.padding_left="${PADDINGS}"                      \
              label.padding_right="${PADDINGS}"                     \
              padding_right="${PADDINGS}"                           \
              padding_left="${PADDINGS}"                            \
              background.height=30                                  \
              background.corner_radius=9                            \
              popup.background.border_width=2                       \
              popup.background.corner_radius=9                      \
              popup.background.border_color="${POPUP_BORDER_COLOR}" \
              popup.background.color="${POPUP_BACKGROUND_COLOR}"    \
              popup.background.shadow.drawing=on

# Left
. "${SKETCHYBAR_ITEM_DIR}/apple.sh"
. "${SKETCHYBAR_ITEM_DIR}/spaces.sh"
. "${SKETCHYBAR_ITEM_DIR}/front_app.sh"

# Center
# . "${SKETCHYBAR_ITEM_DIR}/spotify.sh"

# Right
. "${SKETCHYBAR_ITEM_DIR}/calendar.sh"
. "${SKETCHYBAR_ITEM_DIR}/brew.sh"
. "${SKETCHYBAR_ITEM_DIR}/battery.sh"
. "${SKETCHYBAR_ITEM_DIR}/volume.sh"
. "${SKETCHYBAR_ITEM_DIR}/cpu.sh"
# . "${SKETCHYBAR_ITEM_DIR}/vpn.sh"
. "${SKETCHYBAR_ITEM_DIR}/net.sh"
. "${SKETCHYBAR_ITEM_DIR}/network.sh"

############## FINALIZING THE SETUP ##############

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."