
# min_version = "2024.1.1"

[tools]
argocd = '2.6.1'
cilium-cli = "0.15.20"
cilium-hubble = "0.13.0"
clusterctl = '1.4.3'
helm = '3.12.0'
helm-cr = '1.4.1'
helm-ct = '3.4.0'
kind = '0.16.0'
kubectl = '1.26.0'
kustomize = '5.5.0'
k3sup = '0.13.4'
k9s = "0.31.7"
teleport-ent = '12.3.2'
terraform = '1.4.6'
terraform-docs = '0.16.0'
tflint = '0.42.2'
tfsec = '1.28.1'
trivy = "latest"
vault = "1.15.4"
timoni = "0.19.0"
mimirtool = "2.11.0"
k6 = "0.49.0"
melange = "latest"
apko = "latest"
k3d = "5.6.0"
node = "latest"
java = "23-loom+2-48.0.0"
