[settings]
legacy_version_file = true # enabled by default (different than asdf)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

verbose = false     # set to true to see full installation output, see `RTX_VERBOSE`
asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `RTX_ASDF_COMPAT`
jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr

experimental = false # enable experimental features such as shims
idiomatic_version_file_enable_tools = ["terraform"]

[tools]
argocd = '2.6.1'
cilium-cli = "0.15.20"
cilium-hubble = "0.13.0"
clusterctl = '1.4.3'
helm = '3.12.0'
helm-cr = '1.4.1'
helm-ct = "3.11.0"
kubectl = "1.30.1"
k3sup = '0.13.4'
k9s = "0.40.3"
teleport-ent = "13.4.0"
terraform-docs = '0.16.0'
tflint = '0.42.2'
tfsec = '1.28.1'
vault = "1.15.4"
timoni = "0.19.0"
mimirtool = "2.11.0"
k6 = "0.49.0"
melange = "latest"
apko = "latest"
k3d = "5.6.0"
node = "latest"
java = "23-loom+2-48.0.0"
dagger = "0.11.9"
rye = "0.38.0"
xh = "0.22.2"
pint = "0.64.0"
terraform = "1.9.5"
opentofu = "1.8.1"
kubeconform = "0.6.7"
datree = "1.9.19"
pluto = "5.20.2"
talosctl = "1.7.6"
trivy = "0.55.2"
talhelper = "3.0.5"
terragrunt = "latest"
promtool = "latest"
kustomize = "5.4.3"
kind = "0.25.0"
opa = "1.0.0"
boundary = "0.15.1"
helm-docs = "1.14.2"
teleport-community = "13.4.0"
duckdb = "1.3.0"
dive = "latest"
oras = "1.2.3"
